### PR TITLE
Tweaked sizing code for sunburst charts`

### PR DESCRIPTION
**Pull request by andy-lee-eng**
Leads to large charts with more space usage, when divided into columns

### CODE REVIEW

**Review by Ro4052 — DISMISSED** [review]

**Comment by Ro4052** [comment]
Originally, this wouldn't have had to scroll:

image

There was also no legend overlap (this could be fixed by #143):

image

**Comment by andy-lee-eng** [comment]
This is what I was seeing:

image

**Comment by andy-lee-eng** [comment]
I prefer the version that scrolls a bit

**Comment by Ro4052** [comment]
Fair enough. I didn't think that issue still happened (I remember seeing it).

**Comment by Ro4052** [comment]
The only other issue was the legend overlap. Which from a quick look might not be solved by #143.

**Comment by andy-lee-eng** [comment]
I've made an adjustment so that it renders smaller charts without scrolling if the row size is "close" (i.e. if the charts are going to be really small, it scrolls instead).

**Comment by andy-lee-eng** [comment]
I think we should have another look at the legend position once we've merged this with #143. It's not overlapping for me.

**Review by Ro4052 — APPROVED** [review]

**Pull request merged**
