### PR TITLE
titling mechanism for gridLayout charts made generic and shared.

### PR DESCRIPTION
**Pull request by redbearsam**

### CODE REVIEW

**Review by mhooper-scottlogic — COMMENTED** [review]
The titles look good on the treemap, but the gap seems to be a bit off for the sunburst.
There is a gap between the bottom of the title and the chart, but the chart below sits right on the title so it makes it look like the title is for the above chart and not vice versa:

image

**Comment by redbearsam** [comment]
I shall investigate.

**Comment by Ro4052** [comment]
> The titles look good on the treemap, but the gap seems to be a bit off for the sunburst.
> There is a gap between the bottom of the title and the chart, but the chart below sits right on the title so it makes it look like the title is for the above chart and not vice versa:
> 
> image

I think this is partly because the sunburst charts are now bigger.

**Comment by Ro4052** [comment]
Also, I think the charts are shifted down slightly.

**Review by mhooper-scottlogic — APPROVED** [review]

**Pull request merged**
