### PR TITLE
Refactor axis to use common implementation for x and y

### PR DESCRIPTION
**Pull request by andy-lee-eng**
Instead of organising by "cross" and "main" axis, we now arrange the code by type of axis (time/linear/ordinal).

The type is picked by a common "factory" implementation, leading to a set of X-axis affecting components which can then be passed into the chart using a reusable chart "factory".

### CODE REVIEW

**Review by mhooper-scottlogic — COMMENTED** [review]
Looking good so far. 
I have a couple of observations:
1) The vertical gridlines have been removed for heatmaps. Is this intentional to fix issue (https://int.scottlogic.co.uk/jira/browse/IPJS-88)?
2) Integer numbers are now formatted so that they have a comma for thousands. e.g. 1,100. 
This has an unfortunate effect when the cross axis is a year. E.g. 2000, 2002, 2004 become 2,000; 2,002 etc:
image

3) The height of the heatmap seems to have been affected in some instances:
http://localhost:3000/streaming/streaming.heatmap.html

image

4) For the specific example that Andrew referenced in his issue:
https://github.com/jpmorganchase/perspective/issues/499

The chart now displays points, which is great. The sub-category axis, however, is not quite correct as the lines do not line up with the labels correctly:
image

**Comment by mhooper-scottlogic** [comment]
I have also ran the puppeteer tests. Most passed, some of the heatmaps failed because of the vertical lines being removed, but some also some tests failed because the numbers on the legend seem to have changed slightly. I assume the underlying data hasn't changed, so it is slightly odd that this has happened. I am not sure if it indicates a problem:

before:
image

after:
image

**Comment by andy-lee-eng** [comment]
1. Not intentional, will fix.
2 & 3. We can either enable numeric axis for all charts, or disable them for some charts if you prefer not to have it.
4. I am looking into options for dealing with this.

(5). I cannot see any reason for the change in heatmap colour range. However, I am planning to change that soon anyway (in a separate PR), since it will look better with a `.nice()` number range.

**Comment by andy-lee-eng** [comment]
Also, I'll have to take your word for the puppeteer tests, since I can't run any of them anymore.

**Review by mhooper-scottlogic — APPROVED** [review]
I really like the axisFactory and the chartFactory it makes it very neat.

**Pull request merged**
