### PR TITLE
Fixed issue for data with splits and no groups

### PR DESCRIPTION
**Pull request by Ro4052**

### CODE REVIEW

**Review by andy-lee-eng — COMMENTED** [review]
It looks ok, but will conflict with another PR: https://github.com/redbearsam/perspective/pull/31

**Comment by Ro4052** [comment]
It looks like the conflict should be easy to resolve, right?

**Comment by mhooper-scottlogic** [comment]
I have merged #31 as that will need to be added anyway I suspect.

**Comment by Ro4052** [comment]
I'll rebase mine and resolve the conflict

**Comment by andy-lee-eng** [comment]
Should be easy to resolve in git, but I'm not sure how it'll affect your fix.

**Comment by Ro4052** [comment]
Shall I go ahead and merge this?

**Pull request merged**
