### PR TITLE
Zoom y-axis to data on OHLC/Candlestick charts

### PR DESCRIPTION
**Pull request by andy-lee-eng**

### CODE REVIEW

**Review by Ro4052 — APPROVED** [review]
This behaviour is a lot nicer.

**Comment by Ro4052** [comment]
Do we still need the code that calculates the middle of the current y domain? Would this be used in the case than zooming doesn't cause any overflow in the y direction?

**Comment by Ro4052** [comment]
One minor issue is that the bollinger band can go off the chart and there is no way to drag it into view.

image

**Comment by andy-lee-eng** [comment]
> Do we still need the code that calculates the middle of the current y domain? Would this be used in the case than zooming doesn't cause any overflow in the y direction?

This would still be used in other charts I think? e.g. I haven't changed the behaviour of the line chart when it has a date x-axis. Currently, this new behaviour only applies to OHLC charts.

**Comment by andy-lee-eng** [comment]
> One minor issue is that the bollinger band can go off the chart and there is no way to drag it into view.
> 

I don't think this is a big deal. We don't consider the bollinger bands the rest of the time either.

**Comment by Ro4052** [comment]
> > Do we still need the code that calculates the middle of the current y domain? Would this be used in the case than zooming doesn't cause any overflow in the y direction?
> 
> This would still be used in other charts I think? e.g. I haven't changed the behaviour of the line chart when it has a date x-axis. Currently, this new behaviour only applies to OHLC charts.

Ah, yes. I see.

**Pull request merged**
