### PR TITLE
Tooltips for line charts

### PR DESCRIPTION
**Pull request by mhooper-scottlogic**
First attempt at tooltips for line charts.
There are a few issues:
1. The y-axis formatting is messed up when the chart first loads
2. The tooltip does not disappear when the mouse moves off the chart

### CODE REVIEW

**Comment by mhooper-scottlogic** [comment]
The tooltips also only work for line charts with an ordinal cross value (e.g. time based does not work).

**Comment by mhooper-scottlogic** [comment]
> The tooltips also only work for line charts with an ordinal cross value (e.g. time based does not work).

This should now be resolved.

**Comment by matt-hooper** [comment]
> First attempt at tooltips for line charts.
> There are a few issues:
> 
> 1. The y-axis formatting is messed up when the chart first loads
> 2. The tooltip does not disappear when the mouse moves off the chart

The tooltip now disappears (most of the time!). If there is only one line e.g. not multiple values or a split-by, the node.isConnected test fails and so the tooltip is not removed. I am investigating further.

**Comment by mhooper-scottlogic** [comment]
This has been superseded by #86

**Pull request closed without merging**
